
spring.application.name=SpringAi

# ? Correct key name
spring.ai.openai.api-key="${API_KEY:}"

# Optional settings for OpenRouter
spring.ai.openai.base-url=https://openrouter.ai/api
spring.ai.openai.chat.options.model=mistralai/mistral-small-3.2-24b-instruct:free

spring.mvc.servlet.path=/
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

spring.main.allow-bean-definition-overriding=true
